In [4]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

import os
os.chdir("/Users/AlanHDLR/Desktop")

# Ejemplo 1

In [6]:
fraudes = pd.read_csv("Fraude.csv")
fraudes

   ID Reembolso    EdoCivil  Ingresos Fraude
0   1        Sí     Soltero    125000     No
1   2        No      Casado    100000     No
2   3        No     Soltero     70000     No
3   4        Sí      Casado    120000     No
4   5        No  Divorciado     95000     Sí
5   6        No      Casado     60000     No
6   7        Sí  Divorciado    220000     No
7   8        No     Soltero     85000     Sí
8   9        No      Casado     75000     No
9  10        No     Soltero     90000     Sí

In [9]:
# Columnas de referencia
feature_cols = ["Reembolso", "EdoCivil", "Ingresos"]
X = fraudes[feature_cols].values
y = fraudes.Fraude

In [11]:
# Preprocesamiento para las variables categoricas
from sklearn import preprocessing

Cod_Reembolso = preprocessing.LabelEncoder()
Cod_Reembolso.fit(["Sí", "No"])
X[:,0] = Cod_Reembolso.transform(X[:,0])

Cod_EdoCivil = preprocessing.LabelEncoder()
Cod_EdoCivil.fit(["Soltero", "Casado", "Divorciado"])
X[:,1] = Cod_EdoCivil.transform(X[:,1])

In [13]:
X[0:5]

array([[1, 2, 125000],
       [0, 0, 100000],
       [0, 2, 70000],
       [1, 0, 120000],
       [0, 1, 95000]], dtype=object)

In [15]:
# Para los valores de y se requierten variables cualitativas
y[0:5]

0    No
1    No
2    No
3    No
4    Sí
Name: Fraude, dtype: object

In [17]:
# Creación de grupos de entrenamiento y prueba
# Cuando las bases de datos son muy grandes, un 20% de prueba basta
# Cuando son muy pequeñas. un 30% es mucho mejor 

# Creación de grupos de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

In [19]:
# Crear objeto de clasificación del árbol de decisión
clf = DecisionTreeClassifier()

#A plicación del algortimo de árboles de decisión a los grupos de entrenamiento
clf = clf.fit(X_train, y_train)

# Predicción de las respuestas para el grupo de prueba
y_pred = clf.predict(X_test)

In [21]:
X_test

array([[0, 2, 70000],
       [0, 2, 90000],
       [1, 1, 220000]], dtype=object)

In [23]:
y_pred

array(['Sí', 'Sí', 'No'], dtype=object)

In [25]:
y_test

2    No
9    Sí
6    No
Name: Fraude, dtype: object

In [27]:
# Matriz de confusión
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1, 1],
       [0, 1]], dtype=int64)

In [29]:
# Estadisticas de desempeño
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          No       1.00      0.50      0.67         2
          Sí       0.50      1.00      0.67         1

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3

In [31]:
# Instalación de bibliotecas necesarias para graficar el árbol de decisión
!pip install graphviz
!pip install pydotplus

Requirement already satisfied: graphviz in c:\users\alanhdlr\anaconda3\lib\site-packages (0.21)
Requirement already satisfied: pydotplus in c:\users\alanhdlr\anaconda3\lib\site-packages (2.0.2)
Requirement already satisfied: pyparsing>=2.0.1 in c:\users\alanhdlr\anaconda3\lib\site-packages (from pydotplus) (3.1.2)

In [33]:
# Otras librerias necesarias para visualizar los árboles
from sklearn import tree
import graphviz
import pydotplus
from PIL import Image

In [35]:
# Creación de información para el árbol (reglas de decisión)
dot_data = tree.export_graphviz(clf, out_file = None, feature_names = feature_cols, class_names = ["No fraude", "Fraude"])

# Creación de la grafica del árbol
graph = pydotplus.graph_from_dot_data(dot_data)

In [37]:
import os
# Cambia la ruta por la carpeta 'bin' donde se instaló Graphviz en tu PC
os.environ["PATH"] += os.pathsep + 'C:/Program Files/Graphviz/bin'

# Creación del árbol en formato PDF
graph.write_pdf("fraudes.pdf")

# Creación del árbol en formato PNG
graph.write_png("fraudes.png")

image = Image.open("fraudes.png")
image.show()

# Ejemplo 2

In [40]:
pima = pd.read_csv("diabetes.csv")
pima.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [50]:
col_names = ["pregnant", "glucose", "bp", "skin", "insulin", "bmi", "pedigree", "age", "label"]

In [52]:
pima = pd.read_csv("diabetes.csv", header = None, names = col_names)
pima.head()

,pregnant,glucose,bp,skin,insulin,bmi,pedigree,age,label
0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,6,148,72,35,0,33.6,0.627,50,1
2,1,85,66,29,0,26.6,0.351,31,0
3,8,183,64,0,0,23.3,0.672,32,1
4,1,89,66,23,94,28.1,0.167,21,0

In [54]:
# Eliminar los ancabezados anteriores
df = pima.iloc[1:,:]
df

    pregnant glucose  bp skin insulin   bmi pedigree age label
1          6     148  72   35       0  33.6    0.627  50     1
2          1      85  66   29       0  26.6    0.351  31     0
3          8     183  64    0       0  23.3    0.672  32     1
4          1      89  66   23      94  28.1    0.167  21     0
5          0     137  40   35     168  43.1    2.288  33     1
..       ...     ...  ..  ...     ...   ...      ...  ..   ...
764       10     101  76   48     180  32.9    0.171  63     0
765        2     122  70   27       0  36.8     0.34  27     0
766        5     121  72   23     112  26.2    0.245  30     0
767        1     126  60    0       0  30.1    0.349  47     1
768        1      93  70   31       0  30.4    0.315  23     0

[768 rows x 9 columns]

In [56]:
# Seleccion de caracteristicas
feature_cols = ['pregnant', 'insulin', 'bmi', 'age', 'glucose', 'bp', 'pedigree']
X = df[feature_cols]
y = df.label

In [58]:
X

    pregnant insulin   bmi age glucose  bp pedigree
1          6       0  33.6  50     148  72    0.627
2          1       0  26.6  31      85  66    0.351
3          8       0  23.3  32     183  64    0.672
4          1      94  28.1  21      89  66    0.167
5          0     168  43.1  33     137  40    2.288
..       ...     ...   ...  ..     ...  ..      ...
764       10     180  32.9  63     101  76    0.171
765        2       0  36.8  27     122  70     0.34
766        5     112  26.2  30     121  72    0.245
767        1       0  30.1  47     126  60    0.349
768        1       0  30.4  23      93  70    0.315

[768 rows x 7 columns]

In [60]:
y

1      1
2      0
3      1
4      0
5      1
      ..
764    0
765    0
766    0
767    1
768    0
Name: label, Length: 768, dtype: object

In [62]:
# Creación de grupos de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [64]:
# Existen 2 criterios a tener en cuenta
# Criterio de "Gini"
# Criterio de "entriopia"

# Crear objeto de clasificación del árbol de decisión
clf = DecisionTreeClassifier(criterion = 'gini')

#A plicación del algortimo de árboles de decisión a los grupos de entrenamiento
clf = clf.fit(X_train, y_train)

# Predicción de las respuestas para el grupo de prueba
y_pred = clf.predict(X_test)

In [66]:
# Matriz de confusión
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[81, 18],
       [26, 29]], dtype=int64)

In [68]:
# Estadisticas de desempeño
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.76      0.82      0.79        99
           1       0.62      0.53      0.57        55

    accuracy                           0.71       154
   macro avg       0.69      0.67      0.68       154
weighted avg       0.71      0.71      0.71       154

In [70]:
# Creación de información para el árbol (reglas de decisión)
dot_data = tree.export_graphviz(clf, out_file = None, feature_names = feature_cols, class_names = ["Normal", "Diabetes"])

# Creación de la grafica del árbol
graph = pydotplus.graph_from_dot_data(dot_data)

In [72]:
import os
# Cambia la ruta por la carpeta 'bin' donde se instaló Graphviz en tu PC
os.environ["PATH"] += os.pathsep + 'C:/Program Files/Graphviz/bin'

# Creación del árbol en formato PDF
graph.write_pdf("diabetes.pdf")

# Creación del árbol en formato PNG
graph.write_png("diabetes.png")

image = Image.open("diabetes.png")
image.show()

# Optimización de desempeño del árbol de decisión

In [83]:
# Se puede definir una maxima profundidad
# Crear objeto de clasificación del árbol de decisión
clf = DecisionTreeClassifier(criterion = 'entropy', max_depth = 3)

#A plicación del algortimo de árboles de decisión a los grupos de entrenamiento
clf = clf.fit(X_train, y_train)

# Predicción de las respuestas para el grupo de prueba
y_pred = clf.predict(X_test)

# Se puede probar con distintos niveles de profundidad ya que no siempre más profundidad = más precisión

In [77]:
# Estadisticas de desempeño
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.89      0.85        99
           1       0.76      0.64      0.69        55

    accuracy                           0.80       154
   macro avg       0.79      0.76      0.77       154
weighted avg       0.80      0.80      0.79       154

In [79]:
# Creación de información para el árbol (reglas de decisión)
dot_data = tree.export_graphviz(clf, out_file = None, feature_names = feature_cols, class_names = ["Normal", "Diabetes"])

# Creación de la grafica del árbol
graph = pydotplus.graph_from_dot_data(dot_data)

In [81]:
import os
# Cambia la ruta por la carpeta 'bin' donde se instaló Graphviz en tu PC
os.environ["PATH"] += os.pathsep + 'C:/Program Files/Graphviz/bin'

# Creación del árbol en formato PDF
graph.write_pdf("diabetes.pdf")

# Creación del árbol en formato PNG
graph.write_png("diabetes.png")

image = Image.open("diabetes.png")
image.show()

# Adición de colores al árbol de decisión

In [86]:
from six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz

In [90]:
dot_data = StringIO()
export_graphviz(clf, out_file = dot_data, filled = True, rounded = True, special_characters = True,
               feature_names = feature_cols, class_names = ["Normal", " Diabetes"])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())

In [94]:
# Creación de archivo PNG
from PIL import Image
graph.write_png("Diabetes.png")
image = Image.open("Diabetes.png")
image.show()